/**
 * KaamYaab Firebase Provider Seeding Script
 * serviceAccountKey.json
 * Instructions to run:
 * 1. Initialize npm in this directory if you haven't already:
 *    npm init -y
 * 
 * 2. Install the Firebase Admin SDK:
 *    npm install firebase-admin
 * 
 * 3. Go to Firebase Console -> Project Settings -> Service accounts.
 *    Click "Generate new private key", download the JSON file, and save it in the
 *    same directory as this script as 'serviceAccountKey.json'.
 * 
 * 4. Run the script:
 *    node seedworkers.js
 */

const admin = require('firebase-admin');
const fs = require('fs');
const path = require('path');

// 1. Load service account key
const serviceAccountPath = path.join(__dirname, 'serviceAccountKey.json');

if (!fs.existsSync(serviceAccountPath)) {
  console.error('\x1b[31m%s\x1b[0m', 'Error: serviceAccountKey.js not found!');
  console.log('\nPlease place your Firebase service account private key in this folder as:');
  console.log('\x1b[33m%s\x1b[0m', serviceAccountPath);
  console.log('\nTo get this file:');
  console.log('1. Go to Firebase Console (https://console.firebase.google.com/)');
  console.log('2. Click on your project, then click the gear icon (Project Settings) -> "Service accounts" tab.');
  console.log('3. Click the "Generate new private key" button at the bottom.');
  console.log('4. Download and rename the file to "serviceAccountKey.js".\n');
  process.exit(1);
}

const serviceAccount = require(serviceAccountPath);

// 2. Initialize Firebase Admin
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

// 3. Define fallback embedded mock data if assets file is missing
const mockProviders = [
  {
    "id": "W001",
    "name": "Rashid Khan",
    "phone": "+923000000001",
    "service_category": "Plumbing",
    "skills": ["Pipe Repair", "Leak Fix", "Water Tank Cleaning", "Geyser Repair"],
    "lat": 24.9200,
    "lng": 67.0900,
    "area": "Gulshan",
    "city": "Karachi",
    "dna_score": 850,
    "rating": 4.8,
    "total_jobs": 120,
    "completed_jobs": 115,
    "on_time_rate": 0.95,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.9,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 2500,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "10:00", "11:00", "14:00", "15:00"],
    "review_count": 85,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:00:00Z"
  },
  {
    "id": "W002",
    "name": "Kamran Ali",
    "phone": "+923000000002",
    "service_category": "Electrical",
    "skills": ["Complete Wiring", "UPS Setup", "Generator Repair"],
    "lat": 24.8200,
    "lng": 67.0300,
    "area": "Clifton",
    "city": "Karachi",
    "dna_score": 790,
    "rating": 4.6,
    "total_jobs": 90,
    "completed_jobs": 85,
    "on_time_rate": 0.88,
    "cancellation_rate": 0.05,
    "price_fairness_score": 0.85,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3500,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Wed", "Fri", "Sun"],
    "available_slots": ["10:00", "12:00", "14:00", "16:00"],
    "review_count": 60,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:00:00Z"
  },
  {
    "id": "W003",
    "name": "Usman Tariq",
    "phone": "+923000000003",
    "service_category": "Cleaning",
    "skills": ["Deep Home Cleaning", "Sofa Shampoo", "Carpet Washing"],
    "lat": 24.8100,
    "lng": 67.0500,
    "area": "DHA Karachi",
    "city": "Karachi",
    "dna_score": 910,
    "rating": 4.9,
    "total_jobs": 200,
    "completed_jobs": 198,
    "on_time_rate": 0.98,
    "cancellation_rate": 0.01,
    "price_fairness_score": 0.95,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 1500,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["08:00", "11:00", "13:00", "17:00"],
    "review_count": 150,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T11:00:00Z"
  },
  {
    "id": "W004",
    "name": "Ali Raza",
    "phone": "+923000000004",
    "service_category": "AC Repair",
    "skills": ["AC Servicing", "Gas Refill", "Split AC Installation", "Inverter AC Repair"],
    "lat": 24.9400,
    "lng": 67.0300,
    "area": "North Nazimabad",
    "city": "Karachi",
    "dna_score": 820,
    "rating": 4.7,
    "total_jobs": 150,
    "completed_jobs": 140,
    "on_time_rate": 0.92,
    "cancellation_rate": 0.04,
    "price_fairness_score": 0.88,
    "dispute_count": 1,
    "surge_acceptor": true,
    "base_rate_pkr": 4500,
    "experience_level": "expert",
    "certifications": ["HVAC Certified"],
    "availability": ["Mon", "Tue", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "12:00", "15:00", "18:00"],
    "review_count": 110,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:30:00Z"
  },
  {
    "id": "W005",
    "name": "Bilal Ahmed",
    "phone": "+923000000005",
    "service_category": "Carpentry",
    "skills": ["Custom Furniture Repair", "Door Replacement", "Kitchen Cabinet Fix", "Bed Assembly"],
    "lat": 24.8400,
    "lng": 67.1300,
    "area": "Korangi",
    "city": "Karachi",
    "dna_score": 750,
    "rating": 4.5,
    "total_jobs": 80,
    "completed_jobs": 75,
    "on_time_rate": 0.85,
    "cancellation_rate": 0.08,
    "price_fairness_score": 0.82,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3000,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "available_slots": ["10:00", "11:00", "14:00", "16:00"],
    "review_count": 55,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-19T14:00:00Z"
  },
  {
    "id": "W006",
    "name": "Zainab Bibi",
    "phone": "+923000000006",
    "service_category": "Plumbing",
    "skills": ["Bathroom Fixtures Fix", "Sink Blockage Removal", "Muslim Shower Fix"],
    "lat": 24.8700,
    "lng": 67.0600,
    "area": "PECHS",
    "city": "Karachi",
    "dna_score": 880,
    "rating": 4.9,
    "total_jobs": 110,
    "completed_jobs": 108,
    "on_time_rate": 0.96,
    "cancellation_rate": 0.01,
    "price_fairness_score": 0.92,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 2000,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["09:00", "12:00", "15:00"],
    "review_count": 90,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T08:00:00Z"
  },
  {
    "id": "W007",
    "name": "Tariq Mehmood",
    "phone": "+923000000007",
    "service_category": "Painting",
    "skills": ["Interior Wall Painting", "Exterior Paint", "Waterproofing", "Texture Paint"],
    "lat": 24.9056,
    "lng": 67.0822,
    "area": "Federal B Area",
    "city": "Karachi",
    "dna_score": 800,
    "rating": 4.6,
    "total_jobs": 95,
    "completed_jobs": 90,
    "on_time_rate": 0.91,
    "cancellation_rate": 0.03,
    "price_fairness_score": 0.87,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 2800,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["08:00", "10:00", "13:00", "16:00"],
    "review_count": 70,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:30:00Z"
  },
  {
    "id": "W008",
    "name": "Naseem Akhtar",
    "phone": "+923000000008",
    "service_category": "Pest Control",
    "skills": ["Cockroach Treatment", "Termite Control", "Fumigation", "Dengue Spray"],
    "lat": 24.8615,
    "lng": 67.0099,
    "area": "Saddar",
    "city": "Karachi",
    "dna_score": 835,
    "rating": 4.7,
    "total_jobs": 130,
    "completed_jobs": 125,
    "on_time_rate": 0.94,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.91,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3200,
    "experience_level": "advanced",
    "certifications": ["Pest Control License"],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["09:00", "11:00", "14:00", "17:00"],
    "review_count": 100,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:00:00Z"
  },
  {
    "id": "W009",
    "name": "Shahid Iqbal",
    "phone": "+923000000009",
    "service_category": "Electrical",
    "skills": ["Solar Panel Installation", "Inverter Wiring", "DB Board Setup", "Fan Repair"],
    "lat": 24.9215,
    "lng": 67.1322,
    "area": "Gulistan-e-Johar",
    "city": "Karachi",
    "dna_score": 870,
    "rating": 4.8,
    "total_jobs": 160,
    "completed_jobs": 155,
    "on_time_rate": 0.96,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.93,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 4000,
    "experience_level": "expert",
    "certifications": ["Electrical Safety Certified"],
    "availability": ["Mon", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "11:00", "14:00", "16:00"],
    "review_count": 120,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T08:00:00Z"
  },
  {
    "id": "W010",
    "name": "Farhan Siddiqui",
    "phone": "+923000000010",
    "service_category": "AC Repair",
    "skills": ["Window AC Repair", "Duct Cleaning", "Chiller Maintenance", "Gas Charging"],
    "lat": 24.8960,
    "lng": 67.1380,
    "area": "Scheme 33",
    "city": "Karachi",
    "dna_score": 810,
    "rating": 4.6,
    "total_jobs": 105,
    "completed_jobs": 99,
    "on_time_rate": 0.90,
    "cancellation_rate": 0.05,
    "price_fairness_score": 0.86,
    "dispute_count": 1,
    "surge_acceptor": true,
    "base_rate_pkr": 4200,
    "experience_level": "advanced",
    "certifications": ["HVAC Certified"],
    "availability": ["Mon", "Tue", "Thu", "Sat", "Sun"],
    "available_slots": ["10:00", "12:00", "15:00", "18:00"],
    "review_count": 80,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-19T16:00:00Z"
  },
  {
    "id": "W011",
    "name": "Rubina Khatoon",
    "phone": "+923000000011",
    "service_category": "Cleaning",
    "skills": ["Office Cleaning", "Post-Construction Cleanup", "Kitchen Deep Clean", "Glass Cleaning"],
    "lat": 24.8500,
    "lng": 67.0100,
    "area": "Lyari",
    "city": "Karachi",
    "dna_score": 760,
    "rating": 4.4,
    "total_jobs": 65,
    "completed_jobs": 60,
    "on_time_rate": 0.87,
    "cancellation_rate": 0.06,
    "price_fairness_score": 0.83,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 1200,
    "experience_level": "beginner",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "available_slots": ["08:00", "10:00", "13:00"],
    "review_count": 45,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-18T12:00:00Z"
  },
  {
    "id": "W012",
    "name": "Imran Hussain",
    "phone": "+923000000012",
    "service_category": "Welding",
    "skills": ["Iron Gate Fabrication", "Grill Welding", "Steel Structure", "Railing Installation"],
    "lat": 24.8780,
    "lng": 67.1600,
    "area": "Landhi",
    "city": "Karachi",
    "dna_score": 790,
    "rating": 4.5,
    "total_jobs": 88,
    "completed_jobs": 82,
    "on_time_rate": 0.89,
    "cancellation_rate": 0.04,
    "price_fairness_score": 0.85,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3500,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "11:00", "14:00", "17:00"],
    "review_count": 62,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:00:00Z"
  },
  {
    "id": "W013",
    "name": "Asad Malik",
    "phone": "+923000000013",
    "service_category": "Plumbing",
    "skills": ["Overhead Tank Installation", "Pump Repair", "Drainage Cleaning", "Pipe Fitting"],
    "lat": 24.9300,
    "lng": 67.0500,
    "area": "Nazimabad",
    "city": "Karachi",
    "dna_score": 840,
    "rating": 4.7,
    "total_jobs": 140,
    "completed_jobs": 135,
    "on_time_rate": 0.93,
    "cancellation_rate": 0.03,
    "price_fairness_score": 0.89,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 2600,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "11:00", "13:00", "16:00"],
    "review_count": 105,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:15:00Z"
  },
  {
    "id": "W014",
    "name": "Hira Noor",
    "phone": "+923000000014",
    "service_category": "Beautician",
    "skills": ["Home Facial", "Waxing", "Bridal Makeup", "Mehendi"],
    "lat": 24.8650,
    "lng": 67.0750,
    "area": "Bahadurabad",
    "city": "Karachi",
    "dna_score": 895,
    "rating": 4.9,
    "total_jobs": 175,
    "completed_jobs": 173,
    "on_time_rate": 0.97,
    "cancellation_rate": 0.01,
    "price_fairness_score": 0.94,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 2500,
    "experience_level": "expert",
    "certifications": ["Cosmetology Diploma"],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["10:00", "12:00", "14:00", "16:00", "18:00"],
    "review_count": 140,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T11:00:00Z"
  },
  {
    "id": "W015",
    "name": "Saeed Anwar",
    "phone": "+923000000015",
    "service_category": "Carpentry",
    "skills": ["Wooden Flooring", "Ceiling Work", "PVC Panel Installation", "Wardrobe Making"],
    "lat": 24.9100,
    "lng": 67.1900,
    "area": "Malir",
    "city": "Karachi",
    "dna_score": 770,
    "rating": 4.5,
    "total_jobs": 72,
    "completed_jobs": 68,
    "on_time_rate": 0.86,
    "cancellation_rate": 0.07,
    "price_fairness_score": 0.84,
    "dispute_count": 1,
    "surge_acceptor": true,
    "base_rate_pkr": 3200,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Wed", "Fri", "Sat"],
    "available_slots": ["09:00", "12:00", "15:00"],
    "review_count": 50,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-19T13:00:00Z"
  },
  {
    "id": "W016",
    "name": "Pervaiz Gul",
    "phone": "+923000000016",
    "service_category": "Gardening",
    "skills": ["Lawn Mowing", "Tree Trimming", "Plant Nursery Setup", "Drip Irrigation"],
    "lat": 24.8300,
    "lng": 67.0800,
    "area": "Defence (DHA Phase 5)",
    "city": "Karachi",
    "dna_score": 855,
    "rating": 4.8,
    "total_jobs": 145,
    "completed_jobs": 142,
    "on_time_rate": 0.95,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.90,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 2000,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["07:00", "09:00", "11:00", "15:00"],
    "review_count": 112,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T07:30:00Z"
  },
  {
    "id": "W017",
    "name": "Iqbal Shaikh",
    "phone": "+923000000017",
    "service_category": "Electrical",
    "skills": ["CCTV Installation", "Smart Home Wiring", "Intercom Setup", "Cable Management"],
    "lat": 24.9500,
    "lng": 67.0700,
    "area": "Buffer Zone",
    "city": "Karachi",
    "dna_score": 815,
    "rating": 4.6,
    "total_jobs": 98,
    "completed_jobs": 93,
    "on_time_rate": 0.91,
    "cancellation_rate": 0.04,
    "price_fairness_score": 0.88,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3800,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Sat"],
    "available_slots": ["10:00", "12:00", "15:00", "17:00"],
    "review_count": 74,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:45:00Z"
  },
  {
    "id": "W018",
    "name": "Munir Ahmed",
    "phone": "+923000000018",
    "service_category": "AC Repair",
    "skills": ["Cassette AC Repair", "Central AC Maintenance", "Thermostat Replacement", "Coil Cleaning"],
    "lat": 24.8750,
    "lng": 67.0450,
    "area": "Garden",
    "city": "Karachi",
    "dna_score": 800,
    "rating": 4.5,
    "total_jobs": 115,
    "completed_jobs": 108,
    "on_time_rate": 0.89,
    "cancellation_rate": 0.05,
    "price_fairness_score": 0.86,
    "dispute_count": 1,
    "surge_acceptor": true,
    "base_rate_pkr": 4000,
    "experience_level": "advanced",
    "certifications": ["HVAC Certified"],
    "availability": ["Mon", "Tue", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["09:00", "11:00", "14:00", "17:00"],
    "review_count": 88,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:15:00Z"
  },
  {
    "id": "W019",
    "name": "Faisal Nawaz",
    "phone": "+923000000019",
    "service_category": "Painting",
    "skills": ["3D Wall Art", "Epoxy Floor Coating", "Wood Staining", "Spray Painting"],
    "lat": 24.9350,
    "lng": 67.0250,
    "area": "Liaquatabad",
    "city": "Karachi",
    "dna_score": 780,
    "rating": 4.5,
    "total_jobs": 78,
    "completed_jobs": 73,
    "on_time_rate": 0.87,
    "cancellation_rate": 0.06,
    "price_fairness_score": 0.85,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3000,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "12:00", "15:00"],
    "review_count": 56,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-19T15:00:00Z"
  },
  {
    "id": "W020",
    "name": "Sana Perveen",
    "phone": "+923000000020",
    "service_category": "Cleaning",
    "skills": ["Baby Room Sanitization", "Mattress Steam Clean", "Curtain Washing", "Washroom Deep Clean"],
    "lat": 24.8550,
    "lng": 67.1100,
    "area": "Model Colony",
    "city": "Karachi",
    "dna_score": 865,
    "rating": 4.8,
    "total_jobs": 132,
    "completed_jobs": 130,
    "on_time_rate": 0.96,
    "cancellation_rate": 0.01,
    "price_fairness_score": 0.92,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 1800,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["08:00", "10:00", "13:00", "16:00"],
    "review_count": 100,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T08:30:00Z"
  },
  {
    "id": "W021",
    "name": "Ghulam Mustafa",
    "phone": "+923000000021",
    "service_category": "Plumbing",
    "skills": ["Borehole Pump Repair", "Sewage Line Clearing", "Water Meter Fix", "Valve Replacement"],
    "lat": 24.9700,
    "lng": 67.0600,
    "area": "Surjani Town",
    "city": "Karachi",
    "dna_score": 745,
    "rating": 4.3,
    "total_jobs": 60,
    "completed_jobs": 54,
    "on_time_rate": 0.83,
    "cancellation_rate": 0.09,
    "price_fairness_score": 0.80,
    "dispute_count": 1,
    "surge_acceptor": true,
    "base_rate_pkr": 2200,
    "experience_level": "beginner",
    "certifications": [],
    "availability": ["Mon", "Tue", "Thu", "Sat"],
    "available_slots": ["10:00", "14:00", "17:00"],
    "review_count": 38,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-17T11:00:00Z"
  },
  {
    "id": "W022",
    "name": "Nadia Shaheen",
    "phone": "+923000000022",
    "service_category": "Beautician",
    "skills": ["Hair Styling", "Threading", "Eyebrow Shaping", "Herbal Facial"],
    "lat": 24.9020,
    "lng": 67.0680,
    "area": "Gulshan Block 13",
    "city": "Karachi",
    "dna_score": 875,
    "rating": 4.8,
    "total_jobs": 155,
    "completed_jobs": 152,
    "on_time_rate": 0.96,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.91,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 1800,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Fri", "Sat", "Sun"],
    "available_slots": ["10:00", "12:00", "14:00", "16:00"],
    "review_count": 118,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:00:00Z"
  },
  {
    "id": "W023",
    "name": "Hamid Raza",
    "phone": "+923000000023",
    "service_category": "Welding",
    "skills": ["Stainless Steel Work", "Aluminum Fabrication", "Gate Repair", "Balcony Railing"],
    "lat": 24.8450,
    "lng": 67.1450,
    "area": "Korangi Industrial",
    "city": "Karachi",
    "dna_score": 800,
    "rating": 4.6,
    "total_jobs": 92,
    "completed_jobs": 88,
    "on_time_rate": 0.90,
    "cancellation_rate": 0.04,
    "price_fairness_score": 0.87,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3800,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "available_slots": ["08:00", "11:00", "14:00", "17:00"],
    "review_count": 68,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T08:45:00Z"
  },
  {
    "id": "W024",
    "name": "Arshad Mehmood",
    "phone": "+923000000024",
    "service_category": "Carpentry",
    "skills": ["False Ceiling", "Gypsum Board Work", "Partition Wall", "Office Furniture Assembly"],
    "lat": 24.8620,
    "lng": 67.0520,
    "area": "Shahrah-e-Faisal",
    "city": "Karachi",
    "dna_score": 830,
    "rating": 4.7,
    "total_jobs": 118,
    "completed_jobs": 113,
    "on_time_rate": 0.93,
    "cancellation_rate": 0.03,
    "price_fairness_score": 0.89,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3500,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "11:00", "14:00", "16:00"],
    "review_count": 92,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:00:00Z"
  },
  {
    "id": "W025",
    "name": "Junaid Qureshi",
    "phone": "+923000000025",
    "service_category": "Pest Control",
    "skills": ["Bed Bug Treatment", "Rodent Control", "Ant Spray", "Monthly AMC Service"],
    "lat": 24.8200,
    "lng": 67.0700,
    "area": "Clifton Block 9",
    "city": "Karachi",
    "dna_score": 860,
    "rating": 4.8,
    "total_jobs": 148,
    "completed_jobs": 145,
    "on_time_rate": 0.95,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.92,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 3500,
    "experience_level": "expert",
    "certifications": ["Pest Control License"],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["09:00", "11:00", "13:00", "16:00"],
    "review_count": 115,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:30:00Z"
  },
  {
    "id": "W026",
    "name": "Shafiq ur Rehman",
    "phone": "+923000000026",
    "service_category": "Electrical",
    "skills": ["MCB Replacement", "Meter Box Repair", "Earthing Setup", "Light Fixture Installation"],
    "lat": 24.9000,
    "lng": 67.0200,
    "area": "Orangi Town",
    "city": "Karachi",
    "dna_score": 755,
    "rating": 4.3,
    "total_jobs": 55,
    "completed_jobs": 50,
    "on_time_rate": 0.84,
    "cancellation_rate": 0.08,
    "price_fairness_score": 0.80,
    "dispute_count": 1,
    "surge_acceptor": true,
    "base_rate_pkr": 2800,
    "experience_level": "beginner",
    "certifications": [],
    "availability": ["Mon", "Wed", "Fri", "Sat"],
    "available_slots": ["10:00", "13:00", "16:00"],
    "review_count": 34,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-18T14:00:00Z"
  },
  {
    "id": "W027",
    "name": "Raheela Begum",
    "phone": "+923000000027",
    "service_category": "Cleaning",
    "skills": ["Marble Polishing", "Villa Cleaning", "Swimming Pool Area Clean", "Balcony Wash"],
    "lat": 24.8050,
    "lng": 67.0600,
    "area": "DHA Phase 8",
    "city": "Karachi",
    "dna_score": 900,
    "rating": 4.9,
    "total_jobs": 185,
    "completed_jobs": 184,
    "on_time_rate": 0.99,
    "cancellation_rate": 0.00,
    "price_fairness_score": 0.96,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 2500,
    "experience_level": "expert",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["08:00", "10:00", "12:00", "14:00"],
    "review_count": 145,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T07:45:00Z"
  },
  {
    "id": "W028",
    "name": "Khalid Jameel",
    "phone": "+923000000028",
    "service_category": "Plumbing",
    "skills": ["Jacuzzi Repair", "Electric Geyser Fix", "Water Filter Installation", "Mixer Tap Replacement"],
    "lat": 24.8150,
    "lng": 67.0350,
    "area": "Clifton Block 2",
    "city": "Karachi",
    "dna_score": 845,
    "rating": 4.7,
    "total_jobs": 125,
    "completed_jobs": 122,
    "on_time_rate": 0.94,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.90,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3000,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["09:00", "11:00", "14:00", "17:00"],
    "review_count": 98,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:30:00Z"
  },
  {
    "id": "W029",
    "name": "Adnan Baig",
    "phone": "+923000000029",
    "service_category": "Gardening",
    "skills": ["Vertical Garden Setup", "Pot Arrangement", "Fertilizer Application", "Hedge Trimming"],
    "lat": 24.8700,
    "lng": 67.0900,
    "area": "PECHS Block 6",
    "city": "Karachi",
    "dna_score": 820,
    "rating": 4.6,
    "total_jobs": 87,
    "completed_jobs": 83,
    "on_time_rate": 0.91,
    "cancellation_rate": 0.04,
    "price_fairness_score": 0.88,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 1800,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["07:00", "09:00", "11:00", "16:00"],
    "review_count": 66,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T07:00:00Z"
  },
  {
    "id": "W030",
    "name": "Waqas Hussain",
    "phone": "+923000000030",
    "service_category": "Painting",
    "skills": ["Weather Shield Application", "Roof Paint", "Border Design", "Wall Primer"],
    "lat": 24.9420,
    "lng": 67.1100,
    "area": "Gulistan-e-Johar Block 15",
    "city": "Karachi",
    "dna_score": 790,
    "rating": 4.5,
    "total_jobs": 80,
    "completed_jobs": 75,
    "on_time_rate": 0.88,
    "cancellation_rate": 0.05,
    "price_fairness_score": 0.85,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 2700,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Fri", "Sat"],
    "available_slots": ["08:00", "11:00", "14:00"],
    "review_count": 58,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-19T10:00:00Z"
  },
  {
    "id": "W031",
    "name": "Salman Farooq",
    "phone": "+923000000031",
    "service_category": "AC Repair",
    "skills": ["AC PCB Repair", "Compressor Replacement", "Remote Programming", "AC Relocation"],
    "lat": 24.9600,
    "lng": 67.0800,
    "area": "New Karachi",
    "city": "Karachi",
    "dna_score": 810,
    "rating": 4.6,
    "total_jobs": 100,
    "completed_jobs": 95,
    "on_time_rate": 0.91,
    "cancellation_rate": 0.04,
    "price_fairness_score": 0.87,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 4500,
    "experience_level": "advanced",
    "certifications": ["HVAC Certified"],
    "availability": ["Mon", "Tue", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["09:00", "12:00", "15:00", "18:00"],
    "review_count": 75,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:00:00Z"
  },
  {
    "id": "W032",
    "name": "Yasmin Fatima",
    "phone": "+923000000032",
    "service_category": "Beautician",
    "skills": ["Keratin Treatment", "Hair Coloring", "Nail Art", "Bleach & Cleanup"],
    "lat": 24.9250,
    "lng": 67.0800,
    "area": "Federal B Area Block 4",
    "city": "Karachi",
    "dna_score": 850,
    "rating": 4.8,
    "total_jobs": 140,
    "completed_jobs": 138,
    "on_time_rate": 0.96,
    "cancellation_rate": 0.01,
    "price_fairness_score": 0.93,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 2200,
    "experience_level": "expert",
    "certifications": ["Cosmetology Diploma"],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["10:00", "12:00", "14:00", "17:00"],
    "review_count": 108,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:45:00Z"
  },
  {
    "id": "W033",
    "name": "Riaz Uddin",
    "phone": "+923000000033",
    "service_category": "Welding",
    "skills": ["Vehicle Body Repair", "Exhaust Pipe Welding", "Custom Metal Work", "Tank Fabrication"],
    "lat": 24.8830,
    "lng": 67.1700,
    "area": "Landhi Industrial",
    "city": "Karachi",
    "dna_score": 775,
    "rating": 4.4,
    "total_jobs": 68,
    "completed_jobs": 63,
    "on_time_rate": 0.86,
    "cancellation_rate": 0.07,
    "price_fairness_score": 0.83,
    "dispute_count": 1,
    "surge_acceptor": true,
    "base_rate_pkr": 4000,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "available_slots": ["08:00", "11:00", "15:00"],
    "review_count": 46,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-18T13:00:00Z"
  },
  {
    "id": "W034",
    "name": "Owais Mansoor",
    "phone": "+923000000034",
    "service_category": "Electrical",
    "skills": ["Electric Vehicle Charger Install", "3-Phase Wiring", "Transformer Setup", "Power Factor Correction"],
    "lat": 24.8250,
    "lng": 67.1500,
    "area": "Korangi Creek",
    "city": "Karachi",
    "dna_score": 885,
    "rating": 4.9,
    "total_jobs": 165,
    "completed_jobs": 163,
    "on_time_rate": 0.97,
    "cancellation_rate": 0.01,
    "price_fairness_score": 0.94,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 5000,
    "experience_level": "expert",
    "certifications": ["Electrical Safety Certified", "EV Charger Installer"],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "11:00", "13:00", "16:00"],
    "review_count": 130,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T08:00:00Z"
  },
  {
    "id": "W035",
    "name": "Anwar Ul Haq",
    "phone": "+923000000035",
    "service_category": "Plumbing",
    "skills": ["Roof Waterproofing", "Expansion Joint Sealing", "Terrace Leakage Fix", "Chemical Grouting"],
    "lat": 24.8900,
    "lng": 67.0350,
    "area": "Soldier Bazaar",
    "city": "Karachi",
    "dna_score": 820,
    "rating": 4.6,
    "total_jobs": 108,
    "completed_jobs": 103,
    "on_time_rate": 0.92,
    "cancellation_rate": 0.03,
    "price_fairness_score": 0.88,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 3000,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "12:00", "15:00", "17:00"],
    "review_count": 82,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:00:00Z"
  },
  {
    "id": "W036",
    "name": "Danish Karim",
    "phone": "+923000000036",
    "service_category": "Carpentry",
    "skills": ["Kitchen Renovation", "Modular Kitchen", "Countertop Fitting", "Cabinet Hinge Repair"],
    "lat": 24.8480,
    "lng": 67.0820,
    "area": "Bath Island",
    "city": "Karachi",
    "dna_score": 860,
    "rating": 4.8,
    "total_jobs": 138,
    "completed_jobs": 135,
    "on_time_rate": 0.95,
    "cancellation_rate": 0.02,
    "price_fairness_score": 0.91,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 4500,
    "experience_level": "expert",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["09:00", "11:00", "13:00", "16:00"],
    "review_count": 107,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T08:30:00Z"
  },
  {
    "id": "W037",
    "name": "Mushtaq Brohi",
    "phone": "+923000000037",
    "service_category": "Pest Control",
    "skills": ["Snake Removal", "Pigeon Control", "Mosquito Fogging", "Wood Borer Treatment"],
    "lat": 24.9550,
    "lng": 67.0300,
    "area": "Baldia Town",
    "city": "Karachi",
    "dna_score": 740,
    "rating": 4.2,
    "total_jobs": 50,
    "completed_jobs": 44,
    "on_time_rate": 0.82,
    "cancellation_rate": 0.10,
    "price_fairness_score": 0.79,
    "dispute_count": 2,
    "surge_acceptor": true,
    "base_rate_pkr": 2500,
    "experience_level": "beginner",
    "certifications": [],
    "availability": ["Mon", "Wed", "Fri"],
    "available_slots": ["11:00", "14:00", "17:00"],
    "review_count": 30,
    "profile_image": "",
    "is_verified": false,
    "last_active_date": "2024-05-16T12:00:00Z"
  },
  {
    "id": "W038",
    "name": "Zubair Hassan",
    "phone": "+923000000038",
    "service_category": "Painting",
    "skills": ["Stucco Finish", "Oil Paint", "Anti-fungal Paint", "POP Work"],
    "lat": 24.8680,
    "lng": 67.1280,
    "area": "Malir City",
    "city": "Karachi",
    "dna_score": 800,
    "rating": 4.6,
    "total_jobs": 90,
    "completed_jobs": 85,
    "on_time_rate": 0.90,
    "cancellation_rate": 0.05,
    "price_fairness_score": 0.87,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 2900,
    "experience_level": "intermediate",
    "certifications": [],
    "availability": ["Mon", "Tue", "Thu", "Fri", "Sat"],
    "available_slots": ["08:00", "11:00", "14:00", "17:00"],
    "review_count": 68,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T09:00:00Z"
  },
  {
    "id": "W039",
    "name": "Saba Naz",
    "phone": "+923000000039",
    "service_category": "Beautician",
    "skills": ["Pedicure & Manicure", "Skin Whitening Facial", "Eyelash Extension", "Party Makeup"],
    "lat": 24.8750,
    "lng": 67.0680,
    "area": "Gulshan Block 7",
    "city": "Karachi",
    "dna_score": 870,
    "rating": 4.8,
    "total_jobs": 162,
    "completed_jobs": 160,
    "on_time_rate": 0.97,
    "cancellation_rate": 0.01,
    "price_fairness_score": 0.93,
    "dispute_count": 0,
    "surge_acceptor": false,
    "base_rate_pkr": 2000,
    "experience_level": "expert",
    "certifications": ["Cosmetology Diploma"],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "available_slots": ["10:00", "12:00", "14:00", "16:00", "18:00"],
    "review_count": 125,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T10:00:00Z"
  },
  {
    "id": "W040",
    "name": "Pervez Akthar",
    "phone": "+923000000040",
    "service_category": "Gardening",
    "skills": ["Rooftop Garden Design", "Vegetable Garden Setup", "Soil Treatment", "Grass Laying"],
    "lat": 24.9150,
    "lng": 67.0950,
    "area": "North Karachi",
    "city": "Karachi",
    "dna_score": 835,
    "rating": 4.7,
    "total_jobs": 122,
    "completed_jobs": 118,
    "on_time_rate": 0.93,
    "cancellation_rate": 0.03,
    "price_fairness_score": 0.89,
    "dispute_count": 0,
    "surge_acceptor": true,
    "base_rate_pkr": 2200,
    "experience_level": "advanced",
    "certifications": [],
    "availability": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "available_slots": ["07:00", "09:00", "11:00", "15:00"],
    "review_count": 95,
    "profile_image": "",
    "is_verified": true,
    "last_active_date": "2024-05-20T07:30:00Z"
  }
];

// 4. Load providers data
let providers = mockProviders;
const assetPath = path.join(__dirname, 'assets', 'data', 'providers_mock.json');
if (fs.existsSync(assetPath)) {
  try {
    const rawData = fs.readFileSync(assetPath, 'utf8');
    const parsed = JSON.parse(rawData);
    if (parsed && Array.isArray(parsed.providers)) {
      providers = parsed.providers;
      console.log('Successfully loaded provider list from assets/data/providers_mock.json');
    }
  } catch (err) {
    console.warn('Warning: Could not parse assets/data/providers_mock.json. Using fallback embedded mock data.', err.message);
  }
} else {
  console.log('Using fallback embedded mock data (assets/data/providers_mock.json not found).');
}

// 5. Seed Firestore
async function seedData() {
  const collectionRef = db.collection('providers');
  console.log(`Starting to seed ${providers.length} workers/providers into 'providers' collection...`);

  const batch = db.batch();

  providers.forEach((provider) => {
    // Ensure Firestore document ID matches the provider ID (e.g. W001)
    const docRef = collectionRef.doc(provider.id);
    batch.set(docRef, provider);
  });

  try {
    await batch.commit();
    console.log('\x1b[32m%s\x1b[0m', `Successfully seeded ${providers.length} providers to Firestore!`);
  } catch (error) {
    console.error('\x1b[31m%s\x1b[0m', 'Failed to seed data:', error);
  } finally {
    process.exit(0);
  }
}

seedData();
